
def test_return_sum():
    try:
        assert 1 == 2
    except Exception as e:
        print(e)
        raise

